dist: trusty
sudo: required

stages:
  - build
  - deploy

git:
  submodules: false

addons:
  apt:
    packages:
    - sudo

before_install:
    - sudo apt-get -qq update
    - git clone https://github.com/MedicineYeh/axiom-beta-env
    - cd $TRAVIS_BUILD_DIR/axiom-beta-env
    - sudo ./install.sh
    - echo -e 'y\n' | ./prepare_all.sh -i
    - source ./install_command.sh

# Do not use root to test the script
script:
    - cd $TRAVIS_BUILD_DIR
    - bash ./build.sh

download:
  stage: build
  script:
    - cd $TRAVIS_BUILD_DIR && ./build.sh sources_auto_download

pre_install:
  stage: build
  script:
    - cd $TRAVIS_BUILD_DIR && ./build.sh pre_install

prepare:
  stage: build
  script:
    - cd $TRAVIS_BUILD_DIR && ./build.sh prepare

build_package:
  stage: build
  script:
    - cd $TRAVIS_BUILD_DIR && ./build.sh build

post_install:
  stage: build
  script:
    - cd $TRAVIS_BUILD_DIR && ./build.sh post_install

update_image:
  stage: deploy
  script:
    - cd $TRAVIS_BUILD_DIR && echo "hi"

notifications:
  email: false
